name: Typescript Code issue
description: Report issues in Typescript code
title: "[TS]: "
labels: ["ts"]
body:
  - type: markdown
    attributes:
      value: '# TS Issue'
  - type: textarea
    id: description
    attributes:
      label: What issue did you encounter?
      description: |
        Please provide a clear description of the bug.

    validations:
      required: true
  - type: textarea
    id: behavior
    attributes:
      label: What did you expect to happen?
      description: What did you expect to happen instead of the current behavior?
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Additional information
      description:  |
        Details like the Project Version, Operating system in which the bug was encountered.
    validations:
      required: false